cetusSite/cetus3pur/urls.py
from django.urls import path
from . import views

urlpatterns = [

    # root
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),

    # View CETUS logged-in user's profile
    path('userprofile/', views.userprofile, name='CetusUser_Profile'),

    
    # Third Parties
        # view all 3rd parties
    path('tpv/', views.ThirdPartiesView, name='ThirdPartiesView'),
        # view users for a specific 3rd party business
    path('tpvu/<int:thirdparty_id>/', views.ThirdPartyUsersTableView, name='ThirdPartyUsersTableView'),
        # view specific user
    path('user/<int:user_id>/', views.ThirdPartyUserViewEdit, name='userviewedit'),
        # add Third party users
    path('addusers/<int:thirdparty_id>', views.ThirdPartyUsersAdd, name='AddNewUsers'),


    # R-R Managers
    path('rrm/', views.RRRManagersView, name='RRRManagersView'),


    # EAB Requests
    path('eabreq/create/',views.EAB_RequestCreate_cbv.as_view() , name='EABReqCreate' ),
    path('eabreq/edit/<int:pk>',views.EAB_RequestEdit_cbv.as_view()),
    path('eabreq/view/<int:pk>',views.EAB_RequestView_cbv.as_view()),


    # EAB Approvals
    path('eabappr/create/',views.EAB_ApproveCreate_cbv.as_view()),
    path('eabappr/create/<int:reqid>',views.EAB_ApproveCreate_cbv.as_view()),
    path('eabappr/edit/<int:pk>',views.EAB_ApproveEdit_cbv.as_view()),
    path('eabappr/view/<int:pk>',views.EAB_ApproveView_cbv.as_view()),
    path('eabreq_for_approval/',views.EAB_ReviewSelect, name='EAB_ReviewSelect'),


    # EAB "minutes" / records
    path('eabrecords_cbv/',views.EAB_Records_cbv.as_view(), name='EABRecords'),


    # IT Actions
    path('eab_it_action/create/',views.EAB_IT_Action_Create_cbv.as_view()),  
    path('eab_it_action/edit/<int:appr_id>',views.EAB_IT_Action_Edit_cbv.as_view()),
    path('eab_it_action/view/<int:appr_id>',views.EAB_IT_Action_View_cbv.as_view()),
    path('eab_it_action/list', views.EAB_IT_Action_List.as_view(), name='EAB_IT_ActionList'),
    # path('IT_actionlog/',views.IT_ActionLog, name='IT_actionlog'),


    # Data systems
    path('datastoresystems_cbv/',views.datastoresystems_cbv, name='DataStoreSystem'),


    # Audits    
    path('audit/',views.Audit, name='Audit'),	
    
]

cetusSite/cetusSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
import debug_toolbar
from django.conf import settings


urlpatterns = [
    url(r'cetus/^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'cetus/^logout/$', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('cetus/cetus3pur/', include('cetus3pur.urls')),
    path('cetus/', include('cetus3pur.urls')),
    path('cetus/admin/', admin.site.urls),
    path("cetus/select2/", include("django_select2.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

cetusSite/cetus3pur/models.py
from django.db import models
from django.core.exceptions import ValidationError
from .validators import validateUserName



# A 3rd party, e.g. belcan UK
class ThirdParty(models.Model):
    legal_entity_name = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    ad_group_name = models.CharField('AD Group Name', max_length=50, default='AD group todo')
    
    class Meta:
        verbose_name = "3P Business"
        verbose_name_plural = "3P Businesses"

    def __str__(self):
            return self.legal_entity_name + ' [' + self.location + ']'





# A 3rd party employee
class ThirdPartyUser(models.Model):
    firstname = models.CharField('First name', max_length=50)
    familyname = models.CharField('Family name', max_length=50)
    employer = models.ForeignKey(ThirdParty, on_delete=models.CASCADE)
    employee_id = models.CharField('3P Employee ID', max_length=20)
    userac_name = models.CharField('User account name', max_length=10)
    userac_expirydate = models.DateField('Expiry date')

    @classmethod
    def create(cls, nfirstname, nfamilyname, nemployee_id, nuserac, nuseracexp , nemployer_id):
        tpu = cls(
            firstname=nfirstname,
            familyname = nfamilyname,
            employee_id = nemployee_id,
            userac_name = nuserac,
            userac_expirydate = nuseracexp,
            employer = ThirdParty.objects.get(pk = nemployer_id)
        )
        return tpu

    class Meta:
        verbose_name = "3P User"
        verbose_name_plural = "3P Users"

    def __str__(self):
            return (self.firstname + ' @ ' + self.employer.legal_entity_name + " at location " + self.employer.location)









# what datastore is the requestor seeking to share
# implications for approvals, also useful for impact analysis
class EAB_DataStoreSystem(models.Model):
    DATASTORESYSTEM_CHOICES = [
        ('RRCS_APPROVED_CHANNEL',  'Approved Channel'),
        ('RRCS_NOT_APPROVED_CHANNEL',    'Not Approved as a Channel for Export Controlled data'),
    ]

    name = models.CharField(
        'Data Store System name',
        max_length=100,
        default = 'tbd',
    )


    # to store the selection from the standard list of data store systems
    datastoresystem_approved = models.CharField(
        'Data store system channel status',
        max_length=30,
        choices=DATASTORESYSTEM_CHOICES,
        default='RRCS_OTHER',
    )


    class Meta:
        verbose_name = "Data Store System"
        verbose_name_plural = "Data Store System"

    def __str__(self):
        return (self.name)




# A sub-folder, or partition within the data store system which is intended for a particular classification of data
class EAB_DataStoreSystemArea(models.Model):
    name = models.CharField(
        'Area name',
        max_length=100,
        default = 'tbd',
    )

    dss = models.ForeignKey(
        EAB_DataStoreSystem, 
        related_name='dss_areas',
        on_delete=models.CASCADE
    )


    export_classification_PL9009c = models.BooleanField(
        'Intended to contain PL9009.c',
        default=False,
    )

    export_classification_EU_dualuse = models.BooleanField(
        'Intended to contain EU Dual Use',
        default=False,
    )

    export_classification_US_NLR = models.BooleanField(
        'Intended to contain US NLR (no license required)',
        default=False,
    )

    class Meta:
        verbose_name = "Data storage system Area"
        verbose_name_plural = "Data storage system Areas"

    def __str__(self):
            return ' [area:' + self.name + ']'




## EAB Request
class EAB_Request(models.Model):
    date = models.DateField(
        verbose_name = 'Date',
        help_text = 'Date of this EAB request'
    )

    reqstr_userid = models.CharField(
        verbose_name = 'Requester User ID',
        help_text = 'User ID of person making the request',
        max_length=10,
    )

    tp = models.ForeignKey(
        ThirdParty,
        help_text = 'Name and location must be correct',
        verbose_name = 'Third Party',
        related_name='third_party',
        on_delete=models.CASCADE,
    )

    # e.g. integrity, artisan, nas drive
    data_store_system = models.ForeignKey(
        EAB_DataStoreSystem,
        help_text='The IT System that holds the data',
        related_name='data_store_system',
        on_delete=models.CASCADE,
        null=True
    )  # todo : check this use of related_name



    # e.g. T7000 project in Integrity
    data_store_system_area = models.ForeignKey(
        EAB_DataStoreSystemArea,
        help_text='A reposotory, subfolder, or other part of the IT System, which is to be exported (shared with a 3rd party)',
        related_name='data_store_system_area',
        on_delete=models.CASCADE,
        null=True
    )

    rw_or_ro =  models.CharField(
        'Write Permissions',
        max_length=2,
        choices = [ ('RW','Read/Write'), ('RO','Read Only') ],
        default = 'RO',
    )



    # owner of that part of the data store system, e.g. owner of a specific network folder
    data_owner_userid =  models.CharField(
        'Data Owner User ID',
        help_text = 'User ID of the person who owns this data store',
        max_length=10
    )



    # ipecr - if known/needed
    ipecr = models.IntegerField(
        'IPECR #',
        help_text = 'A six digit number, or use 0 if unsure',
        blank = True,
        default=0,
    )





    @classmethod
    def create(cls, ndate, nrqsteruid, ntpid, ndatastore_system, ndatastore_system_area, ndataowneruid , nipecr):
        er = cls(
                    date=ndate,
                    reqstr_userid = nrqsteruid,
                    tp =  ThirdParty.objects.get(pk = ntpid),
                    data_store_system = ndatastore_system,
                    data_store_system_area = ndatastore_system_area,
                    # data_store =ndatastore,
                    data_owner_userid = ndataowneruid,
                    # data_store_export_claim =  nclaim,
                    ipecr = nipecr)
        return er
    

    class Meta:
        verbose_name = "EAB Request"
        verbose_name_plural = "EAB Requests"
        unique_together = [['tp', 'data_store_system','data_store_system_area' ]]


    def clean(self, *args, **kwargs):
        # check if there's a linked approval in an Approved state
        if(EAB_Approval.objects.filter(request__id=self.id).exists()):
            approval = EAB_Approval.objects.get(request__id=self.id)
            if(approval.decision == 'APP'):
                raise ValidationError('This EAB request is locked - ask an Export Control Manager to revoke the related EAB Approval first.')

        if(not validateUserName(self.reqstr_userid)):
            raise ValidationError('User name ' + self.reqstr_userid + ' appears invalid for field requestor user ID')

        if(not validateUserName(self.data_owner_userid)):
            raise ValidationError('User name ' + self.data_owner_userid + ' appears invalid for field Data owner user ID')

        super().clean(*args, **kwargs)


    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


    def __str__(self):
        temp_str = self.reqstr_userid + ' req for ' + str(self.tp) + ' access to ' + str(self.data_store_system)
        temp_str += ' [' + str(self.data_store_system_area) + ']'
        return temp_str




## EAB Approval
class EAB_Approval(models.Model):
    request = models.ForeignKey(EAB_Request, on_delete=models.CASCADE, default = None)
    date = models.DateField('Date of Review')
    approver_userid = models.CharField('Approver User ID',max_length=10)
    decision =  models.CharField('Decision', max_length=3, choices = [ ('NYR','Not Yet Reviewed'),('APP','Approved'),('REJ','Rejected'),('PEN','Pending')])
    ecm_comment = models.CharField('ECM comment' , max_length=512) # Export Control Manager
    ipm_comment = models.CharField('IP Manager comment', max_length=512) # IP manager
    IT_comment = models.CharField('IT Comment', max_length=512) # IT comment


    @classmethod
    def create(cls, nreq, ndate, napprover, ndecision, necm_comment , nipm_comment, nIT_comment):
        aprv = cls(
                    request = EAB_Request.objects.get(pk = nreq),
                    date = ndate,
                    approver_userid = napprover,
                    decision =  ndecision,
                    ecm_comment = necm_comment,
                    ipm_comment = nipm_comment,
                    IT_comment =  nIT_comment
                    )
        return aprv


    class Meta:
        verbose_name = "EAB Approval"
        verbose_name_plural = "EAB Approvals"


    # debug setting flag here
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


    def __str__(self):
        return self.approver_userid + ' reviewed as ' + self.decision + ' on ' + str(self.date) + ' for request ' + str(self.request)




class EAB_IT_Action(models.Model):

    approval = models.ForeignKey(
        EAB_Approval,
        on_delete=models.CASCADE,
        default = None
    )

    date_assigned = models.DateField('Date action assigned')

    date_completed = models.DateField(
        'Date action completed',
        blank = True,
        null = True,
    )

    IT_executor_userid = models.CharField(
        'IT executor user ID',
        max_length=10,
        blank = True,
        null = True,
    )

    completed = models.BooleanField(
        'Action completed',
        default = False,
    )



    class Meta:
        verbose_name = "EAB IT Action"
        verbose_name_plural = "EAB IT Actions"



    def clean(self, *args, **kwargs):
        # check if there's a linked approval in an Approved state
        if(not self.approval.decision == 'APP'):

cetusSite/cetus3pur/forms.py
from django import forms
from django.forms.models import inlineformset_factory, formset_factory
from django.forms import ModelChoiceField
from cetusSite import settings
from pprint import pprint
import datetime
from django_select2.forms import ModelSelect2Widget, Select2Widget
from .models import (
    EAB_Request,
    EAB_Approval,
    EAB_DataStoreSystem,
    EAB_DataStoreSystemArea,
    EAB_IT_Action,
)


class EAB_Approve_Form(forms.ModelForm):

    date = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(format="%d/%m/%Y"),
        help_text="Date of EAB approval",
    )

    class Meta:
        model = EAB_Approval
        exclude = ()
        fields = "__all__"

    # if creating, set request field of approval object
    def __init__(self, *args, **kwargs):
        initial = kwargs.get("initial", {})
        if "reqid" in kwargs:
            reqid = kwargs.pop("reqid", None)
            initial["request"] = EAB_Request.objects.get(pk=reqid)

        initial['approver_userid'] =  kwargs.pop("user", None)
        dt = datetime.datetime.now()
        dts = dt.strftime('%d/%m/%Y')
        initial['date'] = dts
        super(EAB_Approve_Form, self).__init__(*args, **kwargs)
        
        self.fields['date'].disabled = True
        self.fields['request'].disabled = True
        self.fields['approver_userid'].disabled = True






class EAB_Request_Form(forms.ModelForm):

    date = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(format="%d/%m/%Y"),
        help_text="Date of EAB request",
    )

    data_store_system = forms.ModelChoiceField(
        queryset=EAB_DataStoreSystem.objects.all(),
        widget=Select2Widget(
            attrs={
                "data-width": "20em",
            }
        )
    )

    data_store_system_area = forms.ModelChoiceField(
        queryset=EAB_DataStoreSystemArea.objects.all(),
        widget=ModelSelect2Widget(
            model=EAB_DataStoreSystemArea,
            search_fields=["name__icontains"],
            attrs={
                "data-width": "20em",
                'data-minimum-input-length': 0,
            },
            dependent_fields={"data_store_system": "dss"},
        ),
    )

    class Meta:
        model = EAB_Request
        exclude = ()
        fields = "__all__"


    def __init__(self, *args, **kwargs):
        initial = kwargs.get("initial", {})
        initial['reqstr_userid'] =  kwargs.pop("user", None)
        dt = datetime.datetime.now()
        dts = dt.strftime('%d/%m/%Y')
        initial['date'] = dts
        super(EAB_Request_Form, self).__init__(*args, **kwargs)
        
        self.fields['date'].disabled = True
        self.fields['reqstr_userid'].disabled = True




class EAB_IT_Action_Form(forms.ModelForm):

    date_assigned = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(format="%d/%m/%Y"),
        help_text="when action assigned",
    )

    date_completed = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(format="%d/%m/%Y"),
        help_text="when action completed",
    )


    class Meta:
        model = EAB_IT_Action
        exclude = ()
        fields = "__all__"


    # if creating, set request field of approval object
    def __init__(self, *args, **kwargs):
        initial = kwargs.get("initial", {})
        if "appr_id" in kwargs:
            appr_id = kwargs.pop("appr_id", None)
            initial["approval"] = EAB_Approval.objects.get(pk=appr_id)

        initial['IT_executor_userid'] =  kwargs.pop("user", None)

        dt = datetime.datetime.now()
        dts = dt.strftime('%d/%m/%Y')
        initial['date_completed'] = dts

        super(EAB_IT_Action_Form, self).__init__(*args, **kwargs)
        


        self.fields['date_assigned'].disabled = True
        self.fields['date_completed'].disabled = True
        self.fields['approval'].disabled = True
        self.fields['IT_executor_userid'].disabled = True

cetusSite/cetus3pur/templates/cetus3pur/CETUSUser_Logout.html
{% extends "base.html" %} {% block content %}
<section>
    <div class="container">
        <div class="content">
            <br>
            <h1>Logged out</h1>
        </div>
    </div>
</section>

{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/CetusUser_Profile.html
{% extends "base.html" %} {% block content %}
<div class="section">
    <div class="container">
        <div class="box">
            <h3 class="title">User Details:</h3>
            username : {{ user.username}}
            <br>email : {{ user.email}}
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <div class="box">
            <h3 class="title">Your Roles are:</h3>
            {% for grp in user.groups.all %}
                {{grp}}<br>
            {%endfor%}
        </div>
    </div>
</div>





<div class="section">
    <div class="container">
        <div class="box">
            <h3 class="title">Your Permissions are :</h3>
            {% for p in userpermies%}
                {{p}}<br>
            {% endfor %}
        </div>
    </div>
</div>




<div class="section">
    <div class="container">
        <div class="box">
            <h3 class="title">All Available CETUS Permissions:</h3>
            <div class="content">
                {% for perm in permies%}
                    {{perm}} <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/EAB_IT_Action_Create.html
{% extends "base.html" %} {% block content %}

{% load bulma_tags %}


<section>
    <div class="container">
        <div class="content">
            <br>
            <h1>Complete the IT Action</h1>
        </div>
    </div>
</section>



<section>
    <div class="container">
        <form action="" method="post">

          {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="notification is-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="notification is-warning">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

  


            <div class="box">
                {{ form.date_assigned | bulma }}
                {{ form.date_completed | bulma }}
                {{ form.approval | bulma }}
                {{ form.IT_executor_userid | bulma }}
                {{ form.completed | bulma }}
                
                <!--
                <div class="box">
                    <div class="columns">
                        <div class="column">
                            <label class="checkbox">
                                <input type="checkbox" {% if form.completed%}checked{% endif%} disabled>
                                Completed
                            </label>
                            
                        </div>
                    </div>
                </div>
                -->
            </div>


            <div class="control">
                <button class="button is-primary is-rounded">Submit</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/EAB_IT_Actions_List.html
{% extends "base.html" %} {% block content %}



{% load render_table from django_tables2 %}
{% load bulma_tags %}
<section class="section">
    <div class="container">
        {% if filter %}
            <form action="" method="get">
                {{ filter.form | bulma }}
                <input type="submit">
            </form>
        {% endif %}
        <br>
    </div>
    <div class="container">
        {%  render_table table %}
    </div>
</section>


{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/EAB_Records_cbv.html
{% extends "base.html" %} {% block content %}



{% load render_table from django_tables2 %}
{% load bulma_tags %}
<section class="section">
    <div class="container">
        {% if filter %}
            <form action="" method="get">
                {{ filter.form | bulma }}
                <input type="submit">
            </form>
        {% endif %}
        <br>
    </div>
    <div class="container">
        {%  render_table table %}
    </div>
</section>


{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/EAB_RequestCreate.html
{% extends "base.html" %} {% block content %}

{% load bulma_tags %}


<section>
    <div class="container">
        <div class="content">
            <br>
            <h1>Prepare an EAB Request</h1>
        </div>
    </div>
</section>



<section>
    <div class="container">
        <div class="box">
            <form action="" method="post">
                {{ form.media.css }}
            {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="notification is-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="notification is-warning">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

    


                <div class="box">
                    <!-- or use form | bulma -->
                    {{ form.date | bulma }}
                    {{ form.reqstr_userid | bulma }}
                    {{ form.tp | bulma }}
                    <div class="field">
                        <label class="label">Data Store System</label>
                        {{ form.data_store_system }}
                    </div>
                    <div class="field">
                        <label class="label">Data Store System Area</label>
                        {{ form.data_store_system_area }}
                    </div>
                    {{ form.rw_or_ro | bulma }}
                    {{ form.data_owner_userid | bulma }}
                    {{ form.ipecr | bulma }}                
                </div>

                <!-- Hidden field used to track whether an edit is due to submit pressed
                or user changing data_store_system input -->
                <input type="hidden" name="data_store_system_changed" id="data_store_system_changed" value="No">

                <div class="control">
                    {% if perms.cetus3pur.add_eab_request %}
                        <button class="button is-primary is-rounded">Submit</button>
                    {%else%}
                        <button class="button is-primary is-rounded" disabled>Submit</button>
                    {% endif %}
                </div>

                {{ form.media.js }}
            </form>
        </div>
    </div>
</section>
{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/EAB_RequestSubmitted.html
{% extends "base.html" %} {% block content %} Request Submitted - ID: {{req_id}} {% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/EAB_ReviewSelect.html
{% extends "base.html" %} {% block content %}
{% load cetus_tt %}

<section>
    <div class="container">
        <div class="content">
            <br>
            <h1>EAB Requests - Ready for Approval </h1>
        </div>


        <!-- show a table of EAB requests , with option on each to change request or approve it-->
        <table class="table">
            <thead>
                <tr>
                    <th>EAB Request</th>
                    <th>EAB Approval</th>
                    <th>Date of Request</th>
                    <th>Requestor</th>
                    <th>3rd Party</th>
                    <th>Data Store System</th>
                    <th>Data Store System Area</th>
                    <th>Data Store Owner</th>
                    <th>IPECR</th>
                </tr>
            </thead>
            <tbody>


                {% for req in reqlist %}
                    <tr>
                        <td>
                            <a class="button is-link is-small" href="/cetus3pur/eabreq/edit/{{req.id}}">Edit Request</a>
                        </td>

                        
                        <td>
                        {% if dict_req_has_apprv|hash:req.id  %}
                            <a class="button is-link is-small" {% if  perms.cetus3pur.add_eab_approval %}href="/cetus3pur/eabappr/edit/{{dict_req2appr|hash:req.id}}"{% else %}disabled{% endif %}>Edit Approval</a>
                        {% else %}
                            <a class="button is-link is-small" {% if perms.cetus3pur.add_eab_approval %}href="/cetus3pur/eabappr/create/{{req.id}}"{% else %} disabled{% endif %}>Create Approval</a>
                        {% endif %}                        
                        </td>

                        <td>{{ req.date }}</td>
                        <td>{{ req.reqstr_userid }}</td>
                        <td>{{ req.tp.legal_entity_name }} ({{req.tp.location}})</td>
                        <td>{{ req.data_store_system }}</td>
                        <td>{{ req.data_store_system_area }}</td>
                        <td>{{ req.data_owner_userid }}</td>
                        <td>{{ req.ipecr }}</td>
                    </tr>
                {% endfor %}


            </tbody>
        </table>
    </div>
</section>

{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/ThirdPartiesView.html
{% extends "base.html" %} {% block content %} {% load cetus_tt %}
<!-- MAIN CONTENT -->
<div class="container">
    {% if latest_3p_list %}
    <div class="content">
        <br>
        <h1>List of 3rd Parties</h1>
    </div>
    <div class="tile is-ancestor">
        {% for tp in latest_3p_list %}
        <div class="tile is-parent">
            <article class="tile is-child box">
                <p class="title">
                    <a href="/cetus3pur/tpvu/{{ tp.id }}/"> {{ tp.legal_entity_name }} - {{ tp.location }}</a></p>
                <p class="subtitle">Members : {{ dict3p|hash:tp.legal_entity_name }}</p>
                <p class="subtitle">AD Group : {{ tp.ad_group_name }}</p>
            </article>
        </div>
        {% endfor %} {% else %}
        <p>No 3rd parties are in the cetus database.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/ThirdPartyUsersTableView.html
{% extends "base.html" %} {% block content %}

<section>
    <div class="container">
        <div class="content">
            <br>
            <h1>List of users in {{useremp}} </h1>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th>CETUS User ID</th>
                    <th>1st Name</th>
                    <th>Family Name</th>
                    <th>Employee ID</th>
                    <th>User a/c</th>
                    <th>User a/c expiry</th>
                </tr>
            </thead>
            <tbody>

                {% if userlist %} {% for user in userlist %}

                <tr>
                    <td>
                        <a href="/cetus3pur/user/{{ user.id }}/"> {{user.id}}</a>
                    </td>
                    <td>{{ user.firstname }}</td>
                    <td>{{ user.familyname }}</td>
                    <td>{{ user.employee_id }}</td>
                    <td>{{ user.userac_name }}</td>
                    <td>{{ user.userac_expirydate }}</td>
                </tr>

                {% endfor %} {% else %}
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                {% endif %}

            </tbody>
        </table>
        
        
        <form action="/cetus3pur/addusers/{{ thirdparty_id }}">
            <div class="control">
                <button class="button is-primary is-rounded" {% if not perms.cetus3pur.add_thirdpartyuser %}disabled{%endif%}>Add new users</button>
            </div>
        </form>
        
    </div>
</section>

{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/datastoresystems.html
{% extends "base.html" %} {% block content %}

<section>
    <div class="container">
        <div class="content">
            <div class="box">

                <h1>Databases and Folders</h1>
                <div class="content">
                {% for line in report %}
                    {{line}} <br>
                {% endfor %}
                </div>
        </div>
    </div>
</section>
{% endblock %}

cetusSite/cetus3pur/templates/cetus3pur/logout.html
{% extends 'base.html' %} {% block title %}Logged out{% endblock %} {% block content %}
<h2>Logged out</h2>
{% endblock %}